function couleur
global x y x_w y_w x_r x_g x_b y_r y_g y_b
global info RGBtoXYZ XYZtoRGB
global croix boite posinit maxlum compY
close all
maxlum=1.0;
RGBtoXYZ=...
     [ 0.4124 0.3576 0.1805;...
       0.2126 0.7152 0.0722;...
       0.0193 0.1192 0.9505];
compY=[0.299 0.587 0.114];
XYZtoRGB=inv(RGBtoXYZ);
XYZ_R=RGBtoXYZ*[1;0;0];
XYZ_G=RGBtoXYZ*[0;1;0];
XYZ_B=RGBtoXYZ*[0;0;1];
XYZ_W=RGBtoXYZ*maxlum*[1;1;1];
x_r=XYZ_R(1)/sum(XYZ_R);y_r=XYZ_R(2)/sum(XYZ_R);
x_g=XYZ_G(1)/sum(XYZ_G);y_g=XYZ_G(2)/sum(XYZ_G);
x_b=XYZ_B(1)/sum(XYZ_B);y_b=XYZ_B(2)/sum(XYZ_B);
x_w=XYZ_W(1)/sum(XYZ_W);y_w=XYZ_W(2)/sum(XYZ_W);
x=[x_w;x_w];y=[y_w;y_w];
fig=figure(1);
set(fig,...
'MenuBar','none',...
'Color',[0 0 0],...
'NumberTitle','off',...
'Name','Diagrammme de chromaticit�',...
'Units','normal',...
'Position',[5 5 55 90]/100);
subplot('Position',[0.05 0.3 0.9 0.65])
genediag
set(gca,...
'Fontname','Arial','Color',[0 0 0])
hold on
posinit=plot(...
[x_r x_g x_b x_r],[y_r y_g y_b y_r],...
'g',...
x_w,y_w,'xr');
croix=plot(x,y,'w');
hold off

uicontrol(fig,'Style','slider','Units','normalized',...
'BackgroundColor',[0 0 0],'ForegroundColor',[0 0 0],...
'Position',[0.9 0.5 0.05 0.4],'Value',1.0,...
'Callback',@SCB);

boite(1)=uicontrol(fig,...
'Style','frame','Units','normalized',...
'BackgroundColor',[0 0 0],'ForegroundColor',[0 0 0],...
'Position',[0.70 0.07 0.13 0.20]);

boite(2)=uicontrol(fig,...
'Style','frame','Units','normalized',...
'BackgroundColor',[0 0 0],'ForegroundColor',[0 0 0],...
'Position',[0.83 0.07 0.13 0.20]);

boite(3)=uicontrol(fig,...
'Style','frame','Units','normalized',...
'BackgroundColor',[0 0 0],'ForegroundColor',[0 0 0],...
'Position',[0.70 0.02 0.13 0.05]);

boite(4)=uicontrol(fig,...
'Style','frame','Units','normalized',...
'BackgroundColor',[0 0 0],'ForegroundColor',[0 0 0],...
'Position',[0.83 0.02 0.13 0.05]);

uicontrol(fig,...
'Style','pushbutton','String','stop',...
'Interruptible','off','Units','normalized',...
'Callback','close all','Position',[0.02 0.02 0.1 0.1]);

uicontrol(fig,...
'Style','Text','Units','normalized',...
'Fontname','Courier',...
'FontSize',10,...
'Position',[50 65 30 25]/100,...
'HorizontalAlignment','center',...
'String',...
['Click inside the green triangle',...
' to modify the position of the initial color.',...
' Then drag the cursor to observe',...
' the difference between the colors',...
' which depends on the their distance',...
' in the chromatic diagram'],...
'BackgroundColor','k','ForegroundColor','w');

info=zeros(6,2);

for k=1:7
   for l=1:2
      info(k,l) = uicontrol(fig,...
         'Style','Text','Units','normalized',...
         'Fontname','Courier','FontSize',10,...
         'Position',[l*26-12 22-k*3 26 3]/100,...
         'HorizontalAlignment','left',...
         'BackgroundColor','k','ForegroundColor','w');
   end
end
miseajour(x_w,y_w,1)
miseajour(x_w,y_w,2)

set(fig,'WindowButtonDownFcn',@WBD);
set(fig,'WindowButtonMotionFcn',@WBMF);

function WBD(hObjet,~)
position=hObjet.CurrentAxes.CurrentPoint;
xe=position(1,1);ye=position(1,2);
miseajour(xe,ye,1)

function WBMF(hObjet,~)
position=hObjet.CurrentAxes.CurrentPoint;
xe=position(1,1);ye=position(1,2);
miseajour(xe,ye,2)

function SCB(hObjet,~)
global x y maxlum
maxlum=get(hObjet,'Value');
miseajour(x(1),y(1),1);
miseajour(x(2),y(2),2);

function Cs=gammadir(Cl)
Clim=0.0031308;
gain=12.92;expos=2.4;a=0.055;
Cs=zeros(3,1);
for n=1:3
    if Cl(n)<=Clim
        Cs(n)=gain*Cl(n);
    else
        Cs(n)=(1+a)*Cl(n)^(1/expos)-a;
    end
end

function miseajour(xe,ye,index)
global XYZtoRGB RGBtoXYZ x y
global maxlum info posinit boite croix compY
global x_w y_w x_r x_g x_b y_r y_g y_b
XYZ=[xe;ye;1-xe-ye];
RGB=XYZtoRGB*XYZ;
if all(RGB >= 0)
   x(index)=xe;
   y(index)=ye;
   XYZ=RGBtoXYZ*RGB;
   RGB=RGB*maxlum/XYZ(2);
   if any (RGB > 1)
       RGB=RGB/max(RGB);
   end
   XYZ=RGBtoXYZ*RGB;
   set(info(1,index),'String',[' x=' num2str(x(index),3)]);
   set(info(2,index),'String',[' y=' num2str(y(index),3)]);
   set(info(3,index),'String',[' Rouge=' num2str(RGB(1),3)]);
   set(info(4,index),'String',[' Vert=' num2str(RGB(2),3)]);
   set(info(5,index),'String',[' Bleu=' num2str(RGB(3),3)]);
   set(info(6,index),'String',[' luminance=' num2str(XYZ(2),3)]);
   set(info(7,index),'String',[' luma=' num2str(compY*gammadir(RGB),3)]);
   set(croix,'Xdata',x,'Ydata',y);
   set(posinit(1),'Xdata',[x_r x_g x_b x_r],...
   'Ydata',[y_r y_g y_b y_r]);
   set(posinit(2),'Xdata',x_w,'Ydata',y_w);
   set(boite(index),'BackgroundColor',gammadir(RGB));
   set(boite(index),'ForegroundColor',gammadir(RGB));
   Yprime=ones(3,1)*compY*gammadir(RGB);
   set(boite(2+index),'BackgroundColor',Yprime)
   set(boite(2+index),'ForegroundColor',Yprime)
end
