function jpeg (nom)
global qualite info RGB imagecodee nombmp nomjpg
if nargin == 0
   nom='fillebmp';
end
nomracine=nom;
nombmp=[nomracine '.bmp'];
nomjpg=[nomracine '.jpg'];
qualite=80;
RGB=imread(nombmp);
fig=figure(1);
set(fig,...
   'MenuBar','none',...
   'Color',[1 1 1],...
   'Name','Codage d''image avec compression JPEG',...
   'NumberTitle','off',...
   'Units','normal',...
   'Position',[5 5 90 90]/100);
subplot('Position',[0.02 0.25 0.46 0.75])
image(RGB)
axis equal
set(gca,'XTick',[],'YTick',[]);
title('image originale')
zoom on
subplot('Position',[0.52 0.25 0.46 0.75])
imwrite(RGB,nomjpg,'jpeg','Quality',qualite);
imagecodee=image(imread(nomjpg));
axis equal
set(gca,'XTick',[],'YTick',[]);
zoom on
title('image compressée')
fid=fopen(nombmp,'rb');
fseek(fid,0,'eof');
octetbmp=ftell(fid);
fclose(fid);
fid=fopen(nomjpg,'rb');
fseek(fid,0,'eof');
octetjpg=ftell(fid);
fclose(fid);
taux=octetjpg/octetbmp;
uicontrol(fig,...
   'Style','pushbutton',...
   'String','stop',...
   'Interruptible','off',...
   'Units','normalized',...
   'Callback','close all',...
   'Position',[0.02 0.02 0.1 0.1])
uicontrol(...
   'Style','slider',...
   'Units','normalized',...
   'Interruptible','off',...
   'Position',[0.2 0.20 0.6 0.04],...
   'Min',0,'Max',100,...
   'Value',qualite,...
   'SliderStep',[0.001 0.01],...
   'Callback',@SCB...
)
info(1)=uicontrol(fig,...
   'Style','Text',...
   'String',['qualité = ' num2str(qualite,3) ' %'],...
   'FontName','Arial',...
   'FontSize',14,...
   'Units','normal',...
   'Position',[70 7 20 5]/100,...
   'BackgroundColor',[1 1 0],...
   'ForegroundColor',[0 0 0],...
   'HorizontalAlignment','center');
info(2)=uicontrol(fig,...
   'Style','Text',...
   'String',[' taille du fichier original = ' ...
      int2str(octetbmp) ' octets'],...
   'FontName','Arial',...
   'FontSize',12,...
   'Units','normal',...
   'Position',[15 7 50 5]/100,...
   'BackgroundColor',[1 1 0],...
   'ForegroundColor',[0 0 0],...
   'HorizontalAlignment','left');
info(3)=uicontrol(fig,...
   'Style','Text',...
   'String',[' taille du fichier compressé = ' ...
      int2str(octetjpg) ' octets'],...
   'FontName','Arial',...
   'FontSize',12,...
   'Units','normal',...
   'Position',[15 2 50 5]/100,...
   'BackgroundColor',[1 1 0],...
   'ForegroundColor',[0 0 0],...
   'HorizontalAlignment','left');
info(4)=uicontrol(fig,...
   'Style','Text',...
   'String',['taux = ' num2str(100*taux,3) ' %'],...
   'FontName','Arial',...
   'FontSize',14,...
   'Units','normal',...
   'Position',[70 2 20 5]/100,...
   'BackgroundColor',[1 1 0],...
   'ForegroundColor',[0 0 0],...
   'HorizontalAlignment','center');
uicontrol(fig,...
   'Style','Text',...
   'String','Déplacer le curseur pour modifier la qualité',...
   'FontName','Arial',...
   'FontSize',14,...
   'Units','normal',...
   'Position',[5 13 90 5]/100,...
   'BackgroundColor',[1 1 0],...
   'ForegroundColor',[0 0 0],...
   'HorizontalAlignment','center')

function SCB(hObjet,~)
    global qualite info RGB imagecodee nombmp nomjpg
    qualite=get(hObjet,'Value');
    set(info(1),'String',['qualité = ' num2str(qualite,3) ' %']);
    imwrite(RGB,nomjpg,'jpeg','Quality',qualite);
    set(imagecodee,'Cdata',imread(nomjpg));
    fid=fopen(nombmp,'rb');
    fseek(fid,0,'eof');
    octetbmp=ftell(fid);
    fclose(fid);
    fid=fopen(nomjpg,'rb');
    fseek(fid,0,'eof');
    octetjpg=ftell(fid);
    fclose(fid);
    taux=octetjpg/octetbmp;
    set(info(3),'String',[' taille du fichier compressé = ' int2str(octetjpg) ' octets']);
    set(info(4),'String',[' taux = ' num2str(100*taux,3) ' %']);